(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> 'type' object is not iterable"
p3
sS'layer'
p4
S'/var/www/web2py/applications/teste_ldap/controllers/principal.py'
p5
sS'code'
p6
S"# -*- coding: utf-8 -*-\n\n#fun\xc3\xa7\xc3\xa3o de login\ndef login():\n    return auth.login()\n#fun\xc3\xa7\xc3\xa3o index\n@auth.requires_login()\ndef index():\n    #for item in results:\n    #    if item != {}:\n    #        resultado += [list.append(item.as_list())]\n    resultado = [results for results in dict]\n\n    return response.render('principal/index.html',resultado=resultado)\n\ndef logout():\n    return auth.logout()\n\n\nresponse._vars=response._caller(index)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/var/www/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/var/www/web2py/applications/teste_ldap/controllers/principal.py", line 20, in <module>\n  File "/var/www/web2py/gluon/globals.py", line 393, in <lambda>\n    self._caller = lambda f: f()\n  File "/var/www/web2py/gluon/tools.py", line 3440, in f\n    return action(*a, **b)\n  File "/var/www/web2py/applications/teste_ldap/controllers/principal.py", line 12, in index\n    resultado = [results for results in dict]\nTypeError: \'type\' object is not iterable\n'
p11
s.